### PR TITLE
Cleaning up code

### PR DESCRIPTION
**Pull request by achafetz**
setup RProj & update ICPIutilities

### CODE REVIEW

**Comment by noahbartlett** [comment]
The code you wrote isn't writing the "clean.rds" dataset properly. I'm not exactly sure what you did with "01_Consolidate IP Names.R." But can you fix it? 

What is the reasoning behind creating an rds file rather than using the txt file?

**Comment by noahbartlett** [comment]
Where does: "ICPI_MER_Structured_Dataset_PSNU_IM_FY15-16_20180515_v1_1.txt" come from?

**Comment by achafetz** [comment]
What is the error you're getting writing the rds (line 33 I assume)?

The reason to create an rds file is two fold: 1) it saves as a compressed file, taking up a tenth of text file size and 2) when you read it in, it stores all the formatting you adjusted so you don't need to convert columns from logicial or to numeric a second time.

The FY15-16 data is from the link below:
https://www.pepfar.net/OGAC-HQ/icpi/Products/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FProducts%2FICPI%20Data%20Store%2FMER%2FICPI%20MER%20Structured%20Dataset-May%2015%2C%202018%20%28initial%20FY18Q2%20data%29%2FFY15-16&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC00C3CC873FA325DD44884DEFC36053A859&View=%7B58E3102A-C027-4C66-A5C7-84FEBE208B3C%7D

**Comment by achafetz** [comment]
Back to the issues saving as Rds, did you open as a RStudio Project? If you didn't, R won't know the relative path on your machine that the Project creates within the folder structure its working in.

**Comment by noahbartlett** [comment]
The relative path is in the 00. R file. 

(edit: oh. I think that must have been taken out. never mind.)

**Comment by achafetz** [comment]
Correct. So the original script had the following relative path:

`datapath<-"~/GitHub/Me_One_Last_Kiss/Data"`

This is relative since is uses the tilde, but won't necessary work on other machines unless their Me_One_Last_Kiss folder is stored under the GitHub folder.

RProject makes it completely relative, by (essentially) setting folder as the working directory. This way, when someone clones the repo and opens it up, they will always be pointed to the Data/ without R having to know where all the parent folders sit. Pretty cool feature. The user just has to open up the project as a project to make it work. So the new path is just

`datapath<-"Data"`

**Comment by noahbartlett** [comment]
The error I am getting is: 
Error in filter_impl(.data, quo) : 
  Evaluation error: object 'df_tx_old' not found.

I think its something to do with this line: 
#import Archived MSD for TX_NET_NEW Calculation (need FY16Q4 to calc NET NEW in FY17Q1)
  df_tx_old <- read_msd(file.path(datapath,datafile_archive), save_rds = FALSE) %>% 
    filter(df_tx_old, indicator == "TX_CURR")

**Comment by achafetz** [comment]
ahh! the issue is `df_tx_old` included in filter! sorry.
the code should read
```
df_tx_old <- read_msd(file.path(datapath,datafile_archive), save_rds = FALSE) %>%
filter(indicator == "TX_CURR")
```
I originally had it as two separate lines and then combined them. I can do a pull request to fix it.

**Comment by noahbartlett** [comment]
I now can get it to create df_tx_old. But after I've run 01_Consolidate IP Names.R, the file "ICPI_MER_Structured_Dataset_PSNU_IM_FY17-18_20180515_v1_1_FV_Clean.rds" is only 1kb large. 

The only message I'm getting is:
Parsed with column specification:
cols(
  mechanism = col_character(),
  code = col_character(),
  uid = col_character(),
  partner = col_character(),
  primeid = col_integer(),
  agency = col_character(),
  ou = col_character(),
  startdate = col_date(format = ""),
  enddate = col_date(format = "")
)

**Comment by noahbartlett** [comment]
The problem is with rename_official.
It is creating a df_final which is not a dataframe, but rather something pretty much identical to lst_meta

**Comment by achafetz** [comment]
This is the issue I was alluding to in my email that it stalled out while running the function and just returned the list of header names.

I resolved the issues in ICPIutilities a few minutes ago, so you'll need to reinstall that (v1.0.5.1) and probably restart R.

`devtools::install_github("ICPI/ICPIutilities")`

**Comment by noahbartlett** [comment]
I am running the code. But it is taking A LOT longer than it used to. Went out to lunch, came back, and it is still running. Plus the new RDS file is almost 4 gb (larger than the two .txt files combined).

**Comment by achafetz** [comment]
I image it's hung up on reshaping long. It's already a massive dataset and  can't quite get through gather() as noted in #12. 

I'm not sure what's up with the Rds clean file. Below is a screen shot of the  the MSDs. For the PSNUxIM you notice that the Rds is 5% of the txt file size.
image

**Pull request merged**
